# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "vagrant-vm"

  # google cloud
  config.vm.provider :google do |google, override|
    google.google_project_id = "devops"
    google.google_json_key_location = "googlecloudkey.json"
    google.image_family = "ubuntu-2004-lts"
    google.image_project_id = "ubuntu-os-cloud"

    override.ssh.username = "bogotolec"
    override.ssh.private_key_path = "ssh.key"
  end

  # virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
end