apiVersion: v1
kind: Service
metadata:
  name: devops-web-app-service
spec:
  selector:
    app: devops-web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888