apiVersion: v1
kind: Secret
metadata:
  name: nothingimportant
  labels:
    {{- include "devops-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}